CREATE TABLE IF NOT EXISTS folders(
    unique_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    folder_name TEXT NOT NULL,
    folder_id TEXT PRIMARY KEY
);




CREATE TABLE IF NOT EXISTS notes(
    unique_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_name TEXT NOT NULL,
    note_content TEXT NOT NULL,
    folder_id TEXT REFERENCES folders(folder_id),
    folder_name TEXT NOT NULL,
    modified TEXT 
);

